# Generated by Django 4.2.2 on 2023-06-16 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("App support", "App support"),
                            ("Payment support", "Payment support"),
                            ("HR/Jobs", "HR/Jobs"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("message", models.TextField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In progress", "In progress"),
                            ("Resolved", "Resolved"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
